/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'

const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreasRoute,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AreasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/areas': typeof AreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRouteWithChildren
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/institucional': typeof InstitucionalRoute
  '/noticias': typeof NoticiasRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/areas/': typeof AreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/contato'
    | '/equipe'
    | '/institucional'
    | '/noticias'
    | '/areas/$slug'
    | '/areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/equipe'
    | '/institucional'
    | '/noticias'
    | '/areas/$slug'
    | '/areas'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/contato'
    | '/equipe'
    | '/institucional'
    | '/noticias'
    | '/areas/$slug'
    | '/areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  InstitucionalRoute: typeof InstitucionalRoute
  NoticiasRoute: typeof NoticiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof AreasRoute
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof AreasRoute
    }
  }
}

interface AreasRouteChildren {
  AreasSlugRoute: typeof AreasSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasSlugRoute: AreasSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRouteWithChildren,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  InstitucionalRoute: InstitucionalRoute,
  NoticiasRoute: NoticiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
